//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calculateMWT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentInfo
    {
        public int user_id { get; set; }
        public Nullable<int> content_id { get; set; }
        public Nullable<int> comment_id { get; set; }
        public string comment { get; set; }
    
        public virtual AccountInfo AccountInfo { get; set; }
        public virtual MovieInfo MovieInfo { get; set; }
        public virtual TVInfo TVInfo { get; set; }
        public virtual BookInfo BookInfo { get; set; }
        public virtual GameInfo GameInfo { get; set; }
    }
}
