//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calculateMWT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameInfo()
        {
            this.CommentInfoes = new HashSet<CommentInfo>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string developer { get; set; }
        public Nullable<int> hours { get; set; }
        public string info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentInfo> CommentInfoes { get; set; }
    }
}
